name: Check format

on:
  workflow_dispatch:
  push:
    branches: [ master ]
    paths:
      - '**.h'
      - '**.c'
  pull_request:
    branches: [ master ]

jobs:
  check-format:
    name: Check the code formatting

    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: sudo apt-get update -qq && sudo apt-get install -y clang-format-14
    - name: Autogen && configure
      run: |
        ./autogen.sh
        ./configure
    - name: Check format
      run: |
        make format-sources
        git diff-index --exit-code HEAD -- .
