name: Nar

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-macos:
    name: Build on macos
    runs-on: macos-11

    steps:
    - uses: actions/checkout@v2
    - name: Install build dependencies
      run: |
        brew update
        brew install automake
    - uses: actions/setup-java@v2
      with:
        distribution: 'temurin'
        java-version: '8'
        cache: 'maven'
    - name: Build and test the package
      run: mvn test
    - name: Store the build arctifacts
      uses: actions/upload-artifact@v3
      with:
        name: macos-build
        path: target/nar/louis-*

  build-windows:
    name: Build for Windows
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v2
      with:
        distribution: 'temurin'
        java-version: '8'
        cache: 'maven'
    - name: Install build dependencies
      run: |
        sudo apt-get update
        sudo apt-get install texinfo libc6-dev-i386 mingw-w64
    - name: Build and test the package for x86_64
      run: mvn test -Pcross-compile -Dhost.os=w64-mingw32 -Dos.arch=x86_64
    - name: Build and test the package for i686
      run: mvn test -Pcross-compile -Dhost.os=w64-mingw32 -Dos.arch=i686
    - name: Store the build arctifacts
      uses: actions/upload-artifact@v3
      with:
        name: windows-build
        path: target/nar/louis-*

  build-linux:
    name: Build for Linux
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v2
      with:
        distribution: 'temurin'
        java-version: '8'
        cache: 'maven'
    - name: Build and test the package
      run: mvn test
    - name: Build and test the package for i386
      run: mvn test -Dos.arch=i386
    - name: Store the build arctifacts
      uses: actions/upload-artifact@v3
      with:
        name: linux-build
        path: target/nar/louis-*

  nar:
    name: Package nar and publish
    needs: [build-macos, build-windows, build-linux]
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/download-artifact@v3
      with:
        name: windows-build
        path: target/nar
    - uses: actions/download-artifact@v3
      with:
        name: macos-build
        path: target/nar
    - uses: actions/download-artifact@v3
      with:
        name: linux-build
        path: target/nar
    - uses: actions/setup-java@v2
      with:
        distribution: 'temurin'
        java-version: '8'
        cache: 'maven'
        server-id: sonatype-nexus-snapshots # sonatype-nexus-staging
        server-username: MAVEN_USERNAME
        server-password: MAVEN_PASSWORD
    - name: Build the nar
      run: mvn --batch-mode test nar:nar-prepare-package nar:nar-package jar:jar
    - name: Publish package
      run: mvn --batch-mode deploy:deploy
      env:
        MAVEN_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
        MAVEN_PASSWORD: ${{ secrets.SONATYPE_TOKEN }}
