name: Nar

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-macos:
    name: Build on macos
    runs-on: macos-11

    steps:
    - uses: actions/checkout@v2
    - name: Install build dependencies
      run: |
        brew update
        brew install automake
    - name: Build and test the package
      run: mvn test
    - name: Store the build arctifacts
      uses: actions/upload-artifact@v3
      with:
        name: macos-build
        path: target/nar

  build-linux:
    name: Build on Linux
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build and test the package
      run: mvn test
    - name: Store the build arctifacts
      uses: actions/upload-artifact@v3
      with:
        name: linux-build
        path: target/nar

  nar:
    name: Build a nar
    needs: [build-macos, build-linux]
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the nar
      run: mvn nar:nar-prepare-package nar:nar-package jar:jar gpg:sign install:install
