name: Nar

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  nar:
    name: Build a nar

    # we need to run on macos so that we also have binaries for mac in the nar
    runs-on: macos-11

    steps:
    - uses: actions/checkout@v2

    - name: Install docker
      run: brew update && brew install docker

    - name: Build the docker image
      run: docker build -t louis/builder .

    - name: Run the docker image
      run: docker run --rm -v $(pwd):/src louis/builder
