name: Nar

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-macos:
    name: Build on macos
    runs-on: macos-11

    steps:
    - uses: actions/checkout@v2
    - name: Install build dependencies
      run: |
        brew update
        brew install automake
    - uses: actions/setup-java@v2
      with:
        distribution: 'temurin'
        java-version: '8'
        cache: 'maven'
    - name: Build and test the package
      run: mvn test
    - name: Store the build arctifacts
      uses: actions/upload-artifact@v3
      with:
        name: macos-build
        path: target/nar

  build-linux:
    name: Build on Linux
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v2
      with:
        distribution: 'temurin'
        java-version: '8'
        cache: 'maven'
    - name: Build and test the package
      run: mvn test
    - name: Store the build arctifacts
      uses: actions/upload-artifact@v3
      with:
        name: linux-build
        path: target/nar

  build-windows:
    name: Build for Windows
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v2
      with:
        distribution: 'temurin'
        java-version: '8'
        cache: 'maven'
    - name: Install build dependencies
      run: |
        sudo apt-get update
        sudo apt-get install texinfo libc6-dev-i386 mingw-w64
    - name: Build and test the package
      run: mvn test -Pcross-compile -Dhost.os=w64-mingw32 -Dos.arch=x86_64
    - name: Store the build arctifacts
      uses: actions/upload-artifact@v3
      with:
        name: windows-build
        path: target/nar

  nar:
    name: Build a nar
    needs: [build-macos, build-linux, build-windows]
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the nar
      run: mvn nar:nar-prepare-package nar:nar-package jar:jar
